sudo: required
services:
  - docker

before_install:
  - docker build -t syjn99/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true syjn99/react-test npm test

after_success:
  - docker build -t syjn99/multi-client ./client
  - docker build -t syjn99/multi-nginx ./nginx
  - docker build -t syjn99/multi-server ./server
  - docker build -t syjn99/multi-worker ./worker
  # Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push syjn99/multi-client
  - docker push syjn99/multi-nginx
  - docker push syjn99/multi-server
  - docker push syjn99/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-661330646336"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
